#!/bin/bash
#SBATCH -A morri353
#SBATCH --nodes=12
#SBATCH --tasks-per-node=24
#SBATCH --time=20:00:00

module --force purge 

module load gcc/7.3.0
module load openmpi/3.1.4
module load utilities cmake

source ~/OpenFOAM/OpenFOAM-7/etc/bashrc

cd && cd ../../scratch/brown/szamani/OpenFOAM/szamani-7/run/turbulent/T60_U0

foamCleanTutorials

cp 0/alpha.water.orig 0/alpha.water

blockMesh

setFields

decomposePar

mpirun -np 288 evapFoam -parallel

reconstructPar
